### ISSUE TITLE
Suchseite (=Wireframe 2a): Spezialzeichen in Transkription als Tokentrenner missinterpretiert

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#89]
Bestimmte Zeichen werden von ES als Tokentrenner missinterpretiert:

- -, vgl. #54 
- runde Klammer: Suche nach (j)bkꜥ findet nicht nur (j)bkꜥ-n-ḫns.w (709902), sondern auch Belege für j
- + Suche nach 1000+, findet nicht nur 1000+ (dm5964), sondern auch Belege für 1000
- / Suche nach 1/2, findet nicht nur 1/2 (99026), sondern auch Belege für 1

**Comment by JKatzwinkel** [comment]
The attested errors are caused by a failure on the backend side to apply the appropriate analyzers to incoming search queries. The required analyzers however are already in place in [`elasticsearch/settings/indices/lemma.json`](https://github.com/JKatzwinkel/tla-es/blob/main/src/main/resources/elasticsearch/settings/indices/lemma.json), which can be verified by querying the index's `_analyze` endpoint directly (using httpie):
```
http :9200/lemma/_analyze analyzer=transcription_analyzer text="(j)bkꜥ"                             
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 102
content-type: application/json; charset=UTF-8

{
    "tokens": [
        {
            "end_offset": 6,
            "position": 0,
            "start_offset": 1,
            "token": "jbkꜥ",
            "type": "word"
        }
    ]
}
```
Applying the correct analyzer to queries against lemma transcription will therefore be trivial.

**Comment by dwerning** [comment]
Jetzt: https://github.com/thesaurus-linguae-aegyptiae/tla-es/issues/19
